project_id = "wwmftihkwfmyybaooayb"

[functions.study-chat]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.request-account-deletion]
verify_jwt = true

[functions.confirm-account-deletion]
verify_jwt = false
